version: "3.3"

networks:
  carepanel:
    driver: bridge
    name: carepanel
    ipam:
      driver: default

volumes:
  carepanel-dbdata:
    name: carepanel-dbdata

services:
    carepanel-db:
        image: postgres:13-alpine
        container_name: carepanel-db
        restart: unless-stopped
        hostname: carepanel-db
        stop_signal: SIGINT
        ports:
          - ${DBPORT}:5432
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=${DBNAME}
          - POSTGRES_USER=${DBUSER}
          - POSTGRES_PASSWORD=${DBPASSWD}
        volumes:
          - carepanel-dbdata:/var/lib/postgresql/data
        networks:
          - carepanel

    vecinos-app:
      image: ghcr.io/applica2/djangodockerimage:full
      restart: unless-stopped
      container_name: carepanel-app
      hostname: carepanel-app
      user: ${UID}:${GID}
      command: python manage.py runserver 0.0.0.0:${WEBPORT}
      ports:
        - ${WEBPORT}:${WEBPORT}
      volumes: 
        - ./app:/app
      networks:
        - carepanel
