version: "0.0"

networks:
  aikidjango:
    driver: bridge
    name: aikidjango
    ipam:
      driver: default

volumes:
  aikidjango-dbdata:
    name: aikidjango-dbdata

services:
    aikidjango-db:
        image: postgres:13-alpine
        container_name: aikidjango-db
        restart: unless-stopped
        hostname: aikidjango-db
        stop_signal: SIGINT
        ports:
          - ${DBPORT}:5432
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=${DBNAME}
          - POSTGRES_USER=${DBUSER}
          - POSTGRES_PASSWORD=${DBPASSWD}
        volumes:
          - aikidjango-dbdata:/var/lib/postgresql/data
        networks:
          - aikidjango

    vecinos-app:
      image: ghcr.io/sermodi/djangodocker:latest
      restart: unless-stopped
      container_name: aikidjango-app
      hostname: aikidjango-app
      user: ${UID}:${GID}
      command: python manage.py runserver 0.0.0.0:${WEBPORT}
      ports:
        - ${WEBPORT}:${WEBPORT}
      volumes: 
        - ./app:/app
      networks:
        - aikidjango
