version: "3"

networks:
  vineabot:
    driver: bridge
    name: vineabot
    ipam:
      driver: default

volumes:
  vineabot-dbdata:
    name: vineabot-dbdata

services:
    vineabot-db:
        image: postgres:13-alpine
        container_name: vineabot-db
        restart: unless-stopped
        hostname: vineabot-db
        stop_signal: SIGINT
        ports:
          - ${DBPORT}:5432
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=${DBNAME}
          - POSTGRES_USER=${DBUSER}
          - POSTGRES_PASSWORD=${DBPASSWD}
        volumes:
          - vineabot-dbdata:/var/lib/postgresql/data
        networks:
          - vineabot

    vineabot-app:
      image: ghcr.io/sermodi/djangodocker:latest
      restart: unless-stopped
      container_name: vineabot-app
      hostname: vineabot-app
      user: ${UID}:${GID}
      command: python manage.py runserver 0.0.0.0:${WEBPORT}
      ports:
        - ${WEBPORT}:${WEBPORT}
      volumes: 
        - ./app:/app
      networks:
        - vineabot
